type Resource {
  title: String!
  isDeleted: Boolean
  categories: [ResourceCategories!]!
  tags: [String!]
  content: String!

  address: String
  addressDetails: String
  coverImageUrl: String
  hideCoverImage: Boolean
  hours: String
  latitude: Float
  longitude: Float
  phone: String
  placeId: String
  povHeading: Float
  povPitch: Float
  povZoom: Float
  povLatitude: Float
  povLongitude: Float
  requiresReferral: Boolean
  transit: String
  twitter: String
  websiteUrl: String
}

enum ResourceCategories {
  EMPLOYMENT
  HOUSING
  HEALTH
  COMMUNITY
  FOOD
  COUNSELING
  CLOTHES
  LEGAL
  MISC
}

type Query {
  allResources: [Resource!]
}
