type Resource {
  id: ID
  author: User!

  address: String
  addressDetails: String
  categories: [String]
  content: String!
  coverImageUrl: String
  hideCoverImage: Boolean
  hours: String
  isDeleted: Boolean
  latitude: Number
  longitude: Number
  phone: String
  placeId: String
  pov: {
    heading: Number
    pitch: Number
    zoom: Number
  }
  povLatitude: Number
  povLongitude: Number
  requiresReferral: Boolean
  tags: [String!]
  title: String!
  transit: String
  twitter: String
  websiteUrl: String
}

type User {
  id: ID
  name: String!
  resources: [Resource]
  posts: [Post]
}

type Post {
  id: ID
  author: User!
  title: String!
  published: String!
  updated: String
  content: String!
}

type Query {
  allResources(last: Int): [Resource!]!
  allUsers(last: Int): [User!]!
  allPosts(last: Int): [Post!]!
}

type Mutation {
  createUser(name: String!)

  createPost(author: User!, title: String!, published: String!, content: String!)

  createResource(
    author: User!,
    address: String,
    addressDetails: String,
    categories: [String],
    content: String!,
    coverImageUrl: String,
    hideCoverImage: Boolean,
    hours: String,
    isDeleted: Boolean,
    latitude: Number,
    longitude: Number,
    phone: String,
    placeId: String,
    pov: {
      heading: Number,
      pitch: Number,
      zoom: Number
    },
    povLatitude: Number,
    povLongitude: Number,
    requiresReferral: Boolean,
    tags: [String!],
    title: String!,
    transit: String,
    twitter: String,
    websiteUrl: String,
  )
}
